# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\game.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(516, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.points = QtWidgets.QLCDNumber(self.centralwidget)
        self.points.setObjectName("points")
        self.gridLayout.addWidget(self.points, 2, 1, 1, 2)
        self.restartButton = QtWidgets.QPushButton(self.centralwidget)
        self.restartButton.setObjectName("restartButton")
        self.gridLayout.addWidget(self.restartButton, 5, 0, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 5, 1, 1, 1)
        self.intro = QtWidgets.QLabel(self.centralwidget)
        self.intro.setObjectName("intro")
        self.gridLayout.addWidget(self.intro, 0, 0, 1, 1)
        self._score = QtWidgets.QLabel(self.centralwidget)
        self._score.setObjectName("_score")
        self.gridLayout.addWidget(self._score, 2, 0, 1, 1)
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setObjectName("submitButton")
        self.gridLayout.addWidget(self.submitButton, 5, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 496, 294))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ans6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans6.setObjectName("ans6")
        self.gridLayout_2.addWidget(self.ans6, 7, 1, 1, 1)
        self.ans5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans5.setObjectName("ans5")
        self.gridLayout_2.addWidget(self.ans5, 6, 1, 1, 1)
        self.game9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game9.setObjectName("game9")
        self.gridLayout_2.addWidget(self.game9, 10, 0, 1, 1)
        self.game2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game2.setObjectName("game2")
        self.gridLayout_2.addWidget(self.game2, 3, 0, 1, 1)
        self.ans9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans9.setObjectName("ans9")
        self.gridLayout_2.addWidget(self.ans9, 10, 1, 1, 1)
        self.game5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game5.setObjectName("game5")
        self.gridLayout_2.addWidget(self.game5, 6, 0, 1, 1)
        self.game7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game7.setObjectName("game7")
        self.gridLayout_2.addWidget(self.game7, 8, 0, 1, 1)
        self.ans7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans7.setObjectName("ans7")
        self.gridLayout_2.addWidget(self.ans7, 8, 1, 1, 1)
        self.game3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game3.setObjectName("game3")
        self.gridLayout_2.addWidget(self.game3, 4, 0, 1, 1)
        self.ans0 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans0.setObjectName("ans0")
        self.gridLayout_2.addWidget(self.ans0, 0, 1, 1, 1)
        self.ans1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans1.setObjectName("ans1")
        self.gridLayout_2.addWidget(self.ans1, 2, 1, 1, 1)
        self.game0 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game0.setObjectName("game0")
        self.gridLayout_2.addWidget(self.game0, 0, 0, 1, 1)
        self.game4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game4.setObjectName("game4")
        self.gridLayout_2.addWidget(self.game4, 5, 0, 1, 1)
        self.game1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game1.setObjectName("game1")
        self.gridLayout_2.addWidget(self.game1, 2, 0, 1, 1)
        self.ans2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans2.setObjectName("ans2")
        self.gridLayout_2.addWidget(self.ans2, 3, 1, 1, 1)
        self.ans3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans3.setObjectName("ans3")
        self.gridLayout_2.addWidget(self.ans3, 4, 1, 1, 1)
        self.c1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.c1.setEnabled(False)
        self.c1.setText("")
        self.c1.setObjectName("c1")
        self.gridLayout_2.addWidget(self.c1, 2, 2, 1, 1)
        self.game8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game8.setObjectName("game8")
        self.gridLayout_2.addWidget(self.game8, 9, 0, 1, 1)
        self.game6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.game6.setObjectName("game6")
        self.gridLayout_2.addWidget(self.game6, 7, 0, 1, 1)
        self.ans4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans4.setObjectName("ans4")
        self.gridLayout_2.addWidget(self.ans4, 5, 1, 1, 1)
        self.ans8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ans8.setObjectName("ans8")
        self.gridLayout_2.addWidget(self.ans8, 9, 1, 1, 1)
        self.c0 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.c0.setEnabled(False)
        self.c0.setText("")
        self.c0.setObjectName("c0")
        self.gridLayout_2.addWidget(self.c0, 0, 2, 1, 1)
        self.c2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.c2.setEnabled(False)
        self.c2.setText("")
        self.c2.setObjectName("c2")
        self.gridLayout_2.addWidget(self.c2, 3, 2, 1, 1)
        self.c3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.c3.setEnabled(False)
        self.c3.setText("")
        self.c3.setObjectName("c3")
        self.gridLayout_2.addWidget(self.c3, 4, 2, 1, 1)
        self.c4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.c4.setEnabled(False)
        self.c4.setText("")
        self.c4.setObjectName("c4")
        self.gridLayout_2.addWidget(self.c4, 5, 2, 1, 1)
        self.c5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.c5.setEnabled(False)
        self.c5.setText("")
        self.c5.setObjectName("c5")
        self.gridLayout_2.addWidget(self.c5, 6, 2, 1, 1)
        self.c6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.c6.setEnabled(False)
        self.c6.setText("")
        self.c6.setObjectName("c6")
        self.gridLayout_2.addWidget(self.c6, 7, 2, 1, 1)
        self.c7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.c7.setEnabled(False)
        self.c7.setText("")
        self.c7.setObjectName("c7")
        self.gridLayout_2.addWidget(self.c7, 8, 2, 1, 1)
        self.c8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.c8.setEnabled(False)
        self.c8.setText("")
        self.c8.setObjectName("c8")
        self.gridLayout_2.addWidget(self.c8, 9, 2, 1, 1)
        self.c9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.c9.setEnabled(False)
        self.c9.setText("")
        self.c9.setObjectName("c9")
        self.gridLayout_2.addWidget(self.c9, 10, 2, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.restartButton.setText(_translate("MainWindow", "Restart"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.intro.setText(_translate("MainWindow", "Type in the TV Show, which ou think is the closest match to to given String"))
        self._score.setText(_translate("MainWindow", "Score :"))
        self.submitButton.setText(_translate("MainWindow", "Evaluate"))
        self.game9.setText(_translate("MainWindow", "TextLabel"))
        self.game2.setText(_translate("MainWindow", "TextLabel"))
        self.game5.setText(_translate("MainWindow", "TextLabel"))
        self.game7.setText(_translate("MainWindow", "TextLabel"))
        self.game3.setText(_translate("MainWindow", "TextLabel"))
        self.game0.setText(_translate("MainWindow", "Game of Thrones"))
        self.game4.setText(_translate("MainWindow", "TextLabel"))
        self.game1.setText(_translate("MainWindow", "TextLabel"))
        self.game8.setText(_translate("MainWindow", "TextLabel"))
        self.game6.setText(_translate("MainWindow", "TextLabel"))

        self.restartButton.clicked.connect(MainWindow.restart)
        self.submitButton.clicked.connect(MainWindow.submit)
        self.clearButton.clicked.connect(MainWindow.clear)

